version: "3.8"

services:
  app:
    container_name: app-prod
    image: app-prod
    build:
      context: ./
      target: production
      dockerfile: Dockerfile.prod
    volumes:
      - ./src:/app/src
    ports:
      -8080:80
      # - ./src:/app/node_modules
